FROM node:18-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY . .

# Required for hot reloading inside Docker
ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "start"]
